### ISSUE TITLE
Module 'dataset' is missing

### ISSUE THREAD

**Issue by azztt** [gotutiyan/ged_baselines#1]
https://github.com/gotutiyan/ged_baselines/blob/b093193916f2909f21577ea8e6f4bfbd6333f904/token_ged/train.py#L16

The module is missing.
Trying to install with ```pip install dataset``` installs library for [databases](https://pypi.org/project/dataset/).

**Comment by gotutiyan** [comment]
Thank you for your question!
I forgot to push `dataset.py`, so I've uploded it.
It seems to work now.
